package com.vivekgupta.composecoachmark.coachmark

import androidx.compose.ui.geometry.Rect
import androidx.compose.ui.graphics.drawscope.DrawScope

/**
 *@author Vivek Gupta on 13-1-24
 */

interface RevealEffect {
    /**
     * enter animate shape defined by [drawTargetShape] method around target's bound
     */
    suspend fun enterAnimation(targetBounds: Rect)

    /**
     * exit animate shape defined by [drawTargetShape] method around target's bound
     */
    suspend fun exitAnimation(targetBounds: Rect)

    /**
     * draw Target Shape with the given bounds [targetBounds]
     * @param targetBounds Rectangle of the target's bound
     * @param drawScope DrawScope for the drawing the shape
     * @return [Rect] return the new Rectangle(New Bound) generated by the this method
     */
    fun drawTargetShape(targetBounds: Rect, drawScope: DrawScope) : Rect
}


