package com.vivekgupta.composecoachmark.coachmark.core

import androidx.compose.ui.geometry.Rect
import androidx.compose.ui.graphics.drawscope.DrawScope

/**
 * Defines the contract for drawing and animating the "reveal" effect—the visual highlight or
 * cutout—around the target element in a coach mark.
 *
 * Implementations of this interface control the look and animation of the highlighted area.
 */

interface RevealEffect {
    /**
     * enter animate shape defined by [drawTargetShape] method around target's bound
     */
    suspend fun enterAnimation(targetBounds: Rect)

    /**
     * exit animate shape defined by [drawTargetShape] method around target's bound
     */
    suspend fun exitAnimation(targetBounds: Rect)

    /**
     * draw Target Shape with the given bounds [targetBounds]
     * @param targetBounds Rectangle of the target's bound
     * @param drawScope DrawScope for the drawing the shape
     * @return [Rect] return the new Rectangle(New Bound) generated by the this method
     */
    fun drawTargetShape(targetBounds: Rect, drawScope: DrawScope) : Rect
}